#!/bin/bash

MYSQL_CONFIG_PATH=$HOME/.local/config/mysql
if [ ! -d $MYSQL_CONFIG_PATH ]; then
    echo "No such file or directory: $MYSQL_CONFIG_PATH"
    exit 2
fi

# __customs_connect_client username password database host port
__customs_connect_client() {
    if [ -x "$(command -v mycli)" ]; then
        mycli --user=$1 --password=$2 --host=$4 --port=$5 $3
    elif [ -x "$(command -v mysql)" ]; then
        mysql --user=$1 --password=$2 --host=$4 --port=$5 $3
    else
        echo install mysql client first!
    fi
}

__connect_mysql() {
    case "$#" in
        "3") __customs_connect_client $1 $2 $3 'localhost' 3306 ;;
        "4") __customs_connect_client $1 $2 $3 $4 3306 ;;
        "5") __customs_connect_client $1 $2 $3 $4 $5 ;;
        *) echo __connect_mysql username password database [host [port]] ;;
    esac
}

__help() {
    echo "usage: db number or db filename"
    local i=1
    for filename in `ls $MYSQL_CONFIG_PATH`; do
        echo "$i) -> $filename"
        (( i++ ))
    done
}

__enter_mysql() {
    local args=$1
    if [[ $args =~ ^[0-9]+ ]]; then
        local i=1
        for filename in `ls $MYSQL_CONFIG_PATH`; do
            if [[ "$args" == "$i" ]]; then
                __connect_mysql `cat $MYSQL_CONFIG_PATH/$filename`
            fi
            (( i++ ))
        done
    else
        for filename in `ls $MYSQL_CONFIG_PATH`; do
            if [[ "$args" == "$filename" ]]; then
                __connect_mysql `cat $MYSQL_CONFIG_PATH/$filename`
            fi
        done
    fi
}

[[ $# -ne 1 ]] && __help || __enter_mysql $1

