#!/bin/sh
HERE=`dirname $(realpath $0)`

__normalmod() {
	local folder=$1
	[ ! -d $folder ] && return ;
	sudo chmod -R 755 $folder
	find $folder -type f -print0 | sudo xargs -0 chmod -x
}

__help() {
	echo "usage: normalmod folder"
}


[ $# -ne 1 ] && __help || __normalmod $1

