#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import os
import hashlib
import argparse

def getfilemd5(filepath):
    with open(filepath,'rb') as f:
        md5obj = hashlib.md5()
        while True:
            bits = f.read(8096)
            if not bits: break
            md5obj.update(bits)
        return md5obj.hexdigest()

def dorename(folder):
    filemd5 = {}
    for root, dirnames, filenames in os.walk(folder):
        for filename in filenames:
            filepath = os.path.join(root, filename)
            md5path = os.path.join(root, getfilemd5(filepath)) + os.path.splitext(filepath)[1]
            filemd5[filepath] = md5path

    for name, md5name in filemd5.items():
        os.rename(name, md5name)



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="rename all the files in the list of folders to their md5sum")
    parser.add_argument("folders", nargs='+', help="list of searched folders")
    args = parser.parse_args()
    
    for folder in args.folders: 
        dorename(folder)
